### ISSUE TITLE
export style

### ISSUE THREAD

**Issue by xujihui1985** [typed-typings/npm-is-callable#1]
I saw most of the d.ts from are written in `export =` syntax, so I have to use import / require syntax to import this module,  and when I try to write d.ts for my own module, I'm confused with these two form. why not use export default, so I can `import isCallable  from 'is-callable'` ?

```
declare function isCallable(callable: any): void;

export default isCallable;
```

**Comment by xujihui1985** [comment]
I found `export default` doesn't work for an none es6 module....

**Comment by unional** [comment]
Yes. Essentially you need to match the export mechanism of the source.
